services:
  alpine-dotfiles-test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTFILES_REPO: https://github.com/BarunKGP/.dotfiles.git
        BUILDER_BRANCH: feat/go-cli
        DOTFILES_BRANCH: feat/modularize
        INSTALL_FLAGS: --skip-optional
    container_name: alpine-dotfiles-test
    ports:
      - "2222:22"
    environment:
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    networks:
      - dotfiles-test

networks:
  dotfiles-test:
    driver: bridge
