package languages

import (
	"context"
	"fmt"
)

type EnvVar struct {
	Name   string // e.g., "GOROOT"
	Value  string // may contain $HOME or $VAR references
	Quoted bool   // true → export FOO="value", false → export FOO=value
}

type Initialization struct {
	Snippet string // shell snippet, e.g., eval "$(pyenv init --path)"
}

type Provider interface {
	Name() string
	Detect(ctx context.Context) bool
	Env(ctx context.Context) []EnvVar
	Init(ctx context.Context) *Initialization
}

type Registry struct {
	providers []Provider
}

func NewRegistry() *Registry {
	return &Registry{
		providers: []Provider{
			NewGoSystem(),
			NewPythonPyenv(),
			NewNodeNvm(),
		},
	}
}

func (r *Registry) Render(ctx context.Context) (string, error) {
	output := "#!/bin/sh\n# Generated by dotctl env render — do not edit manually\n\n"
	for _, p := range r.providers {
		if !p.Detect(ctx) {
			continue
		}
		for _, e := range p.Env(ctx) {
			if e.Quoted {
				output += fmt.Sprintf("export %s=\"%s\"\n", e.Name, e.Value)
			} else {
				output += fmt.Sprintf("export %s=%s\n", e.Name, e.Value)
			}
		}
		if init := p.Init(ctx); init != nil {
			output += init.Snippet + "\n"
		}
		output += "\n"
	}
	return output, nil
}
